### ISSUE TITLE
provide installation process

### ISSUE THREAD

**Issue by blackkhawkk** [snoopysecurity/dvws-node#14]
Please issue the installation process.please

**Comment by 05t3** [comment]
Hey, Would you mind providing the installation process if i'm setting it up on Xampp

**Comment by snoopysecurity** [comment]
With Xampp, you will need to install nodeJS (https://stackoverflow.com/questions/18136304/how-to-install-nodejs-on-xampp-localhost), and then docker for the postgresql and mongodb environement as well. But you might be better off just installing docker compose on windows (https://docs.docker.com/compose/install/) and then cloning the dvws-node folder and running `docker-compose up`, this will be the quickest way to set everything up on windows: (https://github.com/snoopysecurity/dvws-node#docker-compose)

**Comment by snoopysecurity** [comment]
Hi @Sharmitanmay the setup instructions are here https://github.com/snoopysecurity/dvws-node#set-up-instructions

Is there anything in there that isn't clear?

**Comment by satyaorissa** [comment]
Hello @snoopysecurity , I have a Windows10 Home edition system. I have installed XAMPP. Could you please guide me how I to install the dvws-node to work in my system? I can't install docker as my home edition of Windows10 will not allow. I have spent enough time to find out the solution but no way. Your guidance would be much appreciated. Thanks in advance. I need to setup the dvws Webservice for my testing. Hope you understood my problem.

**Comment by snoopysecurity** [comment]
you really won't be able to get this working with XAMPP sorry, XAMPP is for Apache HTTP Server, MariaDB database, and interpreters for scripts written in the PHP and Perl programming languages. I am using NodeJS with express with mongodb and mysql, you won't get this working with XAMPP.
