### ISSUE TITLE
Errors are not handled properly in controllers/notebook.js

### ISSUE THREAD

**Issue by tienthanh411** [snoopysecurity/dvws-node#20]
In various places in controllers/notebook.js, if there is error, the server will try to respond with both the error and the value that is supposed to be sent when there is no error. For example:

https://github.com/snoopysecurity/dvws-node/blob/master/controllers/notebook.js#L52
![image](https://user-images.githubusercontent.com/349428/126284774-a6e3fb32-098f-4118-ae2d-2721c5d7e59d.png)

This will result in error: "Error: Can't set headers after they are sent."
An "else" statement should be there to prevent such case.

**Comment by snoopysecurity** [comment]
Hi! thanks for reporting this, i believe it is fixed now, can you try testing this again? thanks

**Comment by tienthanh411** [comment]
Thanks! I could see from the code that it is fixed now.
