### ISSUE TITLE
Register feature not working after a certain period

### ISSUE THREAD

**Issue by AymanRbati** [snoopysecurity/dvws-node#22]
I used docker for installation 

This the bug :

![image](https://user-images.githubusercontent.com/21956791/134762254-4e3f7919-2a8b-4b4f-9df3-bb512d03a1fa.png)

**Comment by snoopysecurity** [comment]
Hmmm I can't seem to reproduce this. How long after starting the application did this happen? Were you fuzzing any part of the application before trying to create a new user?

**Comment by snoopysecurity** [comment]
This issue is not a problem anymore
