### ISSUE TITLE
GraphQL Endpoint Does Not Exist

### ISSUE THREAD

**Issue by mleblebici** [snoopysecurity/dvws-node#27]
After installation through docker-compose up, there is no GraphQL endpoint alive. In the solutions for GraphQL Arbitrary File Write, it says there is an GraphQL endpoint listening at port 4000, however, port 4000 is not even open.

**Comment by snoopysecurity** [comment]
Thanks for reporting, i forgot to add the port to docker-compose file, if you git clone the latest version and run docker-compose, the graphql endpoint should be accessible

**Comment by snoopysecurity** [comment]
Fixed and Closed
