### ISSUE TITLE
Application Crash - node_modules/libxmljs/build/Release/xmljs.node: invalid ELF header

### ISSUE THREAD

**Issue by fos111** [snoopysecurity/dvws-node#29]
web_1         | /home/dvws-node/node_modules/bindings/bindings.js:91
web_1         |         throw e
web_1         |         ^
web_1         | 
web_1         | Error: /home/dvws-node/node_modules/libxmljs/build/Release/xmljs.node: invalid ELF header
web_1         |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
web_1         |     at Module.load (node:internal/modules/cjs/loader:981:32)
web_1         |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
web_1         |     at Module.require (node:internal/modules/cjs/loader:1005:19)
web_1         |     at require (node:internal/modules/cjs/helpers:102:18)
web_1         |     at bindings (/home/dvws-node/node_modules/bindings/bindings.js:84:48)
web_1         |     at Object.<anonymous> (/home/dvws-node/node_modules/libxmljs/lib/bindings.js:1:37)
web_1         |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
web_1         |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
web_1         |     at Module.load (node:internal/modules/cjs/loader:981:32) {
web_1         |   code: 'ERR_DLOPEN_FAILED'
web_1         | }
web_1         | [nodemon] app crashed - waiting for file changes before starting...

**Comment by xseman** [comment]
I'm getting same error after `docker-compose up`

**Comment by fos111** [comment]
yeah, it something related to node js modules conflict

**Comment by xseman** [comment]
It's linux libxml binaries problem environment and how libxml was built., may be related https://github.com/libxmljs/libxmljs/issues/550
