### ISSUE TITLE
how can i use it?

### ISSUE THREAD

**Issue by daxin09pp** [snoopysecurity/dvws-node#3]
Where can I see all api & service?

**Comment by snoopysecurity** [comment]
Hi @daxin09pp, To see all the API calls being used, After setup, (https://github.com/snoopysecurity/dvws-node#dvws-node), go to `http://127.0.0.1/api-docs/` e.g. `http://dvws.local/api-docs/`. A soap server also exists in `http://127.0.0.1/dvwsuserservice?wsdl`

**Comment by snoopysecurity** [comment]
Closed, feel free to reopen if you have more questions

**Comment by snoopysecurity** [comment]
I've started a solutions wiki https://github.com/snoopysecurity/dvws-node/wiki, this should explain the flow of the application with the API better

**Comment by daxin09pp** [comment]
Thanks,
