### ISSUE TITLE
docker-compose up ,Unable to start the web

### ISSUE THREAD

**Issue by zmxw** [snoopysecurity/dvws-node#36]
I have used multiple virtual machine tests, but I still can't start them
It prompts SH: 1: NPM: Not found, I don't know how to fix it
![Snipaste_2022-09-09_10-20-15](https://user-images.githubusercontent.com/57754437/189258743-1c4e7c18-d9c7-4ccf-9284-b811f168261b.jpg)
It did not launch successfully
![图片](https://user-images.githubusercontent.com/57754437/189260821-795ae68d-4764-4749-beb7-af3baa20bb86.png)

I hope to get your help

**Comment by tglemser** [comment]
Same here. Tried to pull the docker container. Any help highly appreciated.

**Comment by rover33** [comment]
go into the docker-compose yaml file and change npm run dvws back to npm start

**Comment by tglemser** [comment]
Perfect. Thanks so much!

**Comment by snoopysecurity** [comment]
thanks both for raising this, i've fixed this in master 🥇
