### ISSUE TITLE
Not an Issue - Add SSTI to your Solutions Wiki

### ISSUE THREAD

**Issue by gromhacks** [snoopysecurity/dvws-node#37]
@snoopysecurity first things first I want you to know that this application is pretty awesome! 

Secondly, I wanted to point out that you actually have a stored "Client Side SSTI" issue when you create a user with the following payload as their username `{{'a'.constructor.prototype.charAt=[].join;$eval('x=alert(1)');}}`.

I figured you could add this to your wiki located at https://github.com/snoopysecurity/dvws-node/wiki .

Cheers,
GromHacks

**Comment by snoopysecurity** [comment]
Thanks for raising this, indeed i was missing this issue. Added https://github.com/snoopysecurity/dvws-node/wiki/Client-Side-Template-Injection-(CSTI)

**Comment by gromhacks** [comment]
Sweet! Happy Holidays. I'll let you know if I find any other hidden gems.
