### ISSUE TITLE
Can i get some clue?

### ISSUE THREAD

**Issue by ofwaetne** [snoopysecurity/dvws-node#4]
Hi there,
I'm recently trying to do some research in api security.
And found this github.
Then successfully  build it on my vm .
But I can't found out any vulnerabilities .
Can I get some clue for it ? Such as which api have what kind of vulnerabilities . 
It'll be great if I can have some clues .

Thanks and best regret 
p.s forgive my poor english .

**Comment by snoopysecurity** [comment]
Hey @ofwaetne, you do raise a good point, i ll start writing a wiki for solutions, will link here, expect this in the next week or so

**Comment by ofwaetne** [comment]
> Hey @ofwaetne, you do raise a good point, i ll start writing a wiki for solutions, will link here, expect this in the next week or so

Oh , that's really nice . Thank you

**Comment by snoopysecurity** [comment]
i've started this https://github.com/snoopysecurity/dvws-node/wiki but not all vulnerabilities has been documented.

**Comment by ofwaetne** [comment]
It's just great !
Really great thanks .

**Comment by snoopysecurity** [comment]
closing this, i've written up all solutions here: https://github.com/snoopysecurity/dvws-node/wiki
