### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by charlielj88** [snoopysecurity/dvws-node#41]
try to run 'docker-compose up' in my macbook but observed the following error,
[+] Running 0/3
 ⠴ dvws-mysql Pulling                                                                                                                                                                   5.6s
 ⠴ dvws-mongo Pulling                                                                                                                                                                   5.6s
 ⠿ web Warning                                                                                                                                                                          5.5s
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by snoopysecurity** [comment]
Thanks for raising this, i've pushed a fix, can you try this on the latest version of dvws-node?

**Comment by charlielj88** [comment]
> Thanks for raising this, i've pushed a fix, can you try this on the latest version of dvws-node?

Thank you. I have verified the issue has already been fixed.
