### ISSUE TITLE
Missing api definition in swagger.js?

### ISSUE THREAD

**Issue by vietlq414** [snoopysecurity/dvws-node#5]
I realize that this application include passphase api but it was not defined in Swaager.JS?

**Comment by snoopysecurity** [comment]
Hey, good spot. This is intentional (https://github.com/snoopysecurity/dvws-node/wiki/Hidden-API-Functionality-Exposure) I wanted to ensure that in order to get all API calls, someone would need to 
* Read Swagger File
* Brute force for any potential endpoints
* Spider the application

**Comment by snoopysecurity** [comment]
Closed, do reopen if you have more questions
